---
overwrite: false
defaults:
    GRUB_TIMEOUT: "0"
    GRUB_TIMEOUT_STYLE: "hidden"
    GRUB_DISTRIBUTOR: "NOVA"
    GRUB_CMDLINE_LINUX_DEFAULT: "quiet splash vt.global_cursor_default=0"
    GRUB_GFXPAYLOAD_LINUX: "keep"
