---
efiSystemPartition: "/boot/efi"
userSwapChoices:
    - none
    - file
initialSwapChoice: file
initialPartitioningChoice: erase
allowManualPartitioning: false
drawNestedPartitions: false
alwaysShowPartitionLabels: false
defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4" ]
