---
defaultGroups:
    - adm
    - cdrom
    - dip
    - plugdev
    - sudo
    - lpadmin
autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    sudo
setRootPassword:  false
doReusePassword:  false

userShell: /bin/bash

passwordRequirements:
    minLength: 1
    maxLength: -1

allowWeakPasswords: true
allowWeakPasswordsDefault: true

user:
    shell: /bin/bash
    forbidden_names: [ root ]
